version: "3.9"

services:
  api:
    build: ./api
    environment:
      - DB_URL=postgresql://user:pass@db:5432/url_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  redirect:
    build: ./redirect
    environment:
      - DB_URL=postgresql://user:pass@db:5432/url_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: url_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - redirect

volumes:
  db_data: